### ISSUE TITLE
`data` in `createError()` is missing in response

### ISSUE THREAD

**Issue by ijkml** [h3js/h3#907]
### Environment

node: 22.6.0
bun: 1.1.33

### Reproduction

Run example from repo: https://github.com/unjs/h3/blob/7324eeec854eecc37422074ef9f2aec8a5e4a816/examples/errors.ts#L20-L25
(log below)

### Describe the bug

It's currently not possible to use `err.data` to pass additional data to client-side.

### Additional context

https://github.com/unjs/h3/issues/823#issuecomment-2388428188

### Logs

```sh
{
  "url": "/devices/lol/",
  "statusCode": 500,
  "statusMessage": "",
  "message": "Fatal error",
  "stack": [
    "at createError (./node_modules/h3/dist/index.mjs:78:15)",
    "at badParamError (./.nitro/dev/index.mjs:934:9)",
    "at Object.handler (./.nitro/dev/index.mjs:992:11)",
    "at ./node_modules/h3/dist/index.mjs:1906:43",
    "at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "at async Object.handler (./node_modules/h3/dist/index.mjs:1978:19)",
    "at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2270:7)"
  ]
}
```
```

**Comment by iiio2** [comment]
@ijkml , according to h3 docs, it is recommended to throw errors instead of returning them using `createError` utility. I think you may check it (https://h3.unjs.io/guide/event-handler#responses-types).

**Comment by iiio2** [comment]
@ijkml , according to h3 docs, it is recommended to throw errors instead of returning them using `createError` utility. You may check it (https://h3.unjs.io/guide/event-handler#responses-types).

**Comment by space-otter** [comment]
Hey @nick-w-nick, What do you mean by "is not" framework-agnostic?

createError is basically just a helper function, and it's used to easily handle internal and runtime errors. Throwing an error is commonly used when a function (like a request/response handler) cannot process further.

Just another example would be [Hono's Exception handling](https://hono.dev/docs/api/exception).

**Comment by pi0** [comment]
Example works as expected in the v2 branch with `data` being included.

H3 requires `throw createError({})` as best practice.

(Note: In Nitro and Nuxt, unhandled error `data` field might be omitted).
